# Site settings
title: Cameron Billingham | Software Engineer
author: Cameron Billingham
email: cameronjbillingham@gmail.com
description: >
  A software engineer with a background in film production who 
  enjoys playing with light and sound, working through problems,
  and pressing a fresh mug of coffee.
baseurl: ""
url: http://www.cameronbillingham.com

exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - website.sublime-project
  - website.sublime-workspace

gems:
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
highlighter: pygments
permalink: pretty
