# Site settings
title: Cameron Billingham | Software Engineer
author: Cameron Billingham
email: cameronjbillingham@gmail.com
description: >
  A software engineer with a background in film production who 
  enjoys playing with light and sound, working through problems,
  and pressing a fresh mug of coffee.
baseurl: ""
url: https://cameronbillingham.com

exclude: 
  - README.md
  - Gemfile
  - Gemfile.lock
  - website.sublime-project
  - website.sublime-workspace

gems:
  - jekyll-seo-tag
  - jekyll-feed

collections:
  films:
    output: true
  code:
    output: false

# Google services
google_analytics: UA-85347507-1

# Build settings
highlighter: rouge
permalink: pretty
